services:
  grace-cli:
    build: .
    image: grace-cli:latest
    volumes:
      - ./:/app
      - ./outputs:/app/outputs
    shm_size: '2gb'
    platform: linux/amd64
    gpus: all
    #(Alternative for Swarm-style syntax shown below)
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - capabilities: ["gpu"]
    runtime: nvidia